/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.project.psm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Advertising service. Represents a row in the &quot;ADVERTISING&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.project.psm.model.impl.AdvertisingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.project.psm.model.impl.AdvertisingImpl}.
 * </p>
 *
 * @author jeffreyjarin
 * @see Advertising
 * @see com.project.psm.model.impl.AdvertisingImpl
 * @see com.project.psm.model.impl.AdvertisingModelImpl
 * @generated
 */
public interface AdvertisingModel extends BaseModel<Advertising>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a advertising model instance should use the {@link Advertising} interface instead.
	 */

	/**
	 * Returns the primary key of this advertising.
	 *
	 * @return the primary key of this advertising
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this advertising.
	 *
	 * @param primaryKey the primary key of this advertising
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ads ID of this advertising.
	 *
	 * @return the ads ID of this advertising
	 */
	public long getAdsId();

	/**
	 * Sets the ads ID of this advertising.
	 *
	 * @param adsId the ads ID of this advertising
	 */
	public void setAdsId(long adsId);

	/**
	 * Returns the group ID of this advertising.
	 *
	 * @return the group ID of this advertising
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this advertising.
	 *
	 * @param groupId the group ID of this advertising
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this advertising.
	 *
	 * @return the company ID of this advertising
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this advertising.
	 *
	 * @param companyId the company ID of this advertising
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this advertising.
	 *
	 * @return the user ID of this advertising
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this advertising.
	 *
	 * @param userId the user ID of this advertising
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this advertising.
	 *
	 * @return the user uuid of this advertising
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this advertising.
	 *
	 * @param userUuid the user uuid of this advertising
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this advertising.
	 *
	 * @return the user name of this advertising
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this advertising.
	 *
	 * @param userName the user name of this advertising
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this advertising.
	 *
	 * @return the create date of this advertising
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this advertising.
	 *
	 * @param createDate the create date of this advertising
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this advertising.
	 *
	 * @return the modified date of this advertising
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this advertising.
	 *
	 * @param modifiedDate the modified date of this advertising
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the data1 of this advertising.
	 *
	 * @return the data1 of this advertising
	 */
	public double getData1();

	/**
	 * Sets the data1 of this advertising.
	 *
	 * @param data1 the data1 of this advertising
	 */
	public void setData1(double data1);

	/**
	 * Returns the data2 of this advertising.
	 *
	 * @return the data2 of this advertising
	 */
	public double getData2();

	/**
	 * Sets the data2 of this advertising.
	 *
	 * @param data2 the data2 of this advertising
	 */
	public void setData2(double data2);

	/**
	 * Returns the data3 of this advertising.
	 *
	 * @return the data3 of this advertising
	 */
	public double getData3();

	/**
	 * Sets the data3 of this advertising.
	 *
	 * @param data3 the data3 of this advertising
	 */
	public void setData3(double data3);

	/**
	 * Returns the data4 of this advertising.
	 *
	 * @return the data4 of this advertising
	 */
	public double getData4();

	/**
	 * Sets the data4 of this advertising.
	 *
	 * @param data4 the data4 of this advertising
	 */
	public void setData4(double data4);

	/**
	 * Returns the data5 of this advertising.
	 *
	 * @return the data5 of this advertising
	 */
	public double getData5();

	/**
	 * Sets the data5 of this advertising.
	 *
	 * @param data5 the data5 of this advertising
	 */
	public void setData5(double data5);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Advertising advertising);

	public int hashCode();

	public CacheModel<Advertising> toCacheModel();

	public Advertising toEscapedModel();

	public String toString();

	public String toXmlString();
}